import { strict as assert } from 'node:assert'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'

const app = source('src/App.tsx')
const onboarding = source('src/ui/AdaptiveOnboarding.tsx')
const editor = source('src/ui/ResumeEditor.tsx')
const restore = source('src/ui/RestoreBackup.tsx')
const reupload = source('src/ui/ResumeReupload.tsx')
const bundle = source('src/ui/ApplicationBundle.tsx')
const cover = source('src/llm/coverLetter.ts')
const interview = source('src/llm/interview.ts')
const flexibleSetup = source('src/ui/FlexibleWorkSetup.tsx')
const flexibleHome = source('src/ui/FlexibleWorkHome.tsx')
const settings = source('src/ui/SettingsStep.tsx')
const preferences = source('src/ui/PreferenceControls.tsx')
const intake = source('src/ui/IntakeStep.tsx')
const explore = source('src/ui/ExploreWorkspace.tsx')

assert.doesNotMatch(app, /<KeyGate/)
assert.match(app, /GroqKeyPrompt/)
assert.match(onboarding, /Build my career profile/)
assert.match(onboarding, /Find flexible work/)
assert.match(onboarding, /Restore Klar backup/)
assert.match(onboarding, /Explore Klar/)
assert.match(onboarding, /Continue setup/)
assert.match(onboarding, /Start over/)
assert.match(onboarding, /Manually|manual/i)
assert.match(restore, /inspectBackup/)
assert.match(restore, /passwordRequired/)
assert.match(editor, /Experience/)
assert.match(editor, /Education/)
assert.match(editor, /Skills/)
assert.match(editor, /Projects/)
assert.match(editor, /Certifications/)
assert.match(editor, /Languages/)
assert.match(editor, /Undo/)
assert.match(reupload, /Preview/)
assert.match(bundle, /downloadResumeDocx/)
assert.match(bundle, /printResumeAsPdf/)
assert.match(cover, /evidenceId/)
assert.match(interview, /evidenceIds/)
assert.match(flexibleSetup, /Show me different kinds/)
assert.match(flexibleSetup, /You do not need a résumé/)
assert.match(flexibleSetup, /Add another city/)
assert.match(flexibleSetup, /Availability \(optional\)/)
assert.match(onboarding, /initial=\{flexibleInitial \?\? undefined\}/)
assert.match(onboarding, /Return to Flexible Work/)
assert.match(flexibleHome, /Add résumé for career roles/)
assert.match(settings, /Edit flexible search/)
assert.match(settings, /<SafetyCenter/)
assert.match(app, /canonical \? deriveProfile/)
assert.doesNotMatch(app, /deriveProfile\(\{\s*summary:\s*''/)
assert.match(preferences, /flex shrink-0 flex-nowrap items-center gap-2/)
assert.match(preferences, /compact \? 'sr-only'/)
assert.match(app, /pt-\[61px\]/)
assert.match(onboarding, /sm:grid-cols-\[auto_1fr_auto\]/)
assert.match(onboarding, /min-h-36/)
assert.match(intake, /grid gap-4 sm:grid-cols-2/)
assert.match(editor, /formatCompleteness/)
assert.match(editor, /Namen ergänzen/)
assert.match(explore, /Kundenfeedback-Prozess/)
assert.match(explore, /formatCompleteness/)

console.log('v23-ui.test.ts: all tests passed')

function source(relative: string): string {
  return readFileSync(resolve(process.cwd(), relative), 'utf8')
}