// ============================================================================
// v2.5 — Flexible "prepare & reach out", résumé-free.
//
// The roadmap's v2.5 flexible deliverable, exactly as written: an OFFICIAL-ROUTE
// HANDOFF with the prepared short message and availability shown alongside to
// copy in. Klar never auto-fills, never pre-submits, and never collapses
// applying into one tap — the person always finishes on the employer's own page.
//
// Everything shown here is generated by a deterministic template from the
// person's own flexible profile (src/flexible/prepare.ts), so no API key is
// needed and no experience can be invented.
// ============================================================================
import { useEffect, useMemo, useRef, useState } from 'react'
import { Button, Field, TextInput } from './atoms'
import { useScrollLock } from './useScrollLock'
import { useLocale } from '../i18n/LocaleProvider'
import type { FlexibleWorkPreferences, NormalizedJob } from '../types'
import {
  buildAvailabilitySummary, buildEmployerMessage, printProfileCard,
} from '../flexible/prepare'

export function FlexiblePrepare({
  job,
  preferences,
  onSavePreferences,
  onSaveDraft,
  initialMessage,
  onClose,
}: {
  job: NormalizedJob
  preferences: FlexibleWorkPreferences
  onSavePreferences: (value: FlexibleWorkPreferences) => void | Promise<void>
  /** Autosave hook — persists the message + availability into the packet. */
  onSaveDraft?: (draft: { message: string; availability: string }) => void | Promise<void>
  initialMessage?: string
  onClose: () => void
}) {
  const { locale, t } = useLocale()
  const de = locale === 'de'
  useScrollLock()
  const panelRef = useRef<HTMLDivElement>(null)

  const [name, setName] = useState(preferences.contact?.name ?? '')
  const [email, setEmail] = useState(preferences.contact?.email ?? '')
  const [phone, setPhone] = useState(preferences.contact?.phone ?? '')
  const [copied, setCopied] = useState(false)
  const [savedDetails, setSavedDetails] = useState(false)

  const withContact: FlexibleWorkPreferences = useMemo(
    () => ({ ...preferences, contact: { name, email, phone } }),
    [preferences, name, email, phone],
  )

  const availability = useMemo(() => buildAvailabilitySummary(withContact, de), [withContact, de])
  const generated = useMemo(
    () => buildEmployerMessage({ preferences: withContact, job, de }),
    [withContact, job, de],
  )
  const [message, setMessage] = useState(initialMessage ?? generated)
  const [dirty, setDirty] = useState(Boolean(initialMessage))

  // Regenerate while the person has not hand-edited the text.
  useEffect(() => {
    if (!dirty) setMessage(generated)
  }, [generated, dirty])

  // Autosave the current draft (roadmap: the flexible packet stores the message).
  useEffect(() => {
    if (!onSaveDraft) return
    const timer = setTimeout(() => void onSaveDraft({ message, availability }), 500)
    return () => clearTimeout(timer)
  }, [message, availability, onSaveDraft])

  // Dialog a11y: focus the panel on open and close on Escape (WCAG 2.1.2).
  useEffect(() => {
    panelRef.current?.focus()
    const onKey = (event: KeyboardEvent) => {
      if (event.key === 'Escape') onClose()
    }
    document.addEventListener('keydown', onKey)
    return () => document.removeEventListener('keydown', onKey)
  }, [onClose])

  const openEntry = job.kind === 'open_entry'
  const roleLabel = openEntry ? job.programName ?? job.title : job.title

  async function copyMessage() {
    try {
      await navigator.clipboard.writeText(message)
      setCopied(true)
      setTimeout(() => setCopied(false), 1500)
    } catch {
      /* clipboard blocked — the text stays selectable */
    }
  }

  async function saveDetails() {
    await onSavePreferences(withContact)
    setSavedDetails(true)
    setTimeout(() => setSavedDetails(false), 1500)
  }

  return (
    <div className="fixed inset-0 z-[60] flex justify-end overscroll-contain bg-black/40" onClick={onClose}>
      <div
        ref={panelRef}
        role="dialog"
        aria-modal="true"
        aria-labelledby="flex-prepare-title"
        tabIndex={-1}
        className="app-drawer w-full max-w-xl overflow-y-auto bg-surface p-4 pb-[calc(5.5rem+env(safe-area-inset-bottom))] outline-none sm:p-6 sm:pb-6"
        onClick={(event) => event.stopPropagation()}
      >
        <div className="flex items-start justify-between gap-3">
          <div className="min-w-0 flex-1">
            <h2 id="flex-prepare-title" className="wrap-anywhere text-xl font-semibold text-ink">
              {t('flexPrep.title')}
            </h2>
            <p className="wrap-anywhere text-base text-muted">
              {roleLabel} · {job.employerFamily ?? job.company}
            </p>
          </div>
          <Button variant="ghost" size="sm" className="shrink-0" onClick={onClose} aria-label={t('common.close')}>
            {t('common.close')}
          </Button>
        </div>

        <p className="mt-3 wrap-anywhere text-base leading-relaxed text-muted">{t('flexPrep.intro')}</p>

        <section className="mt-5 rounded-lg border border-border p-4" aria-labelledby="flex-prepare-details">
          <h3 id="flex-prepare-details" className="text-base font-semibold text-ink">
            {t('flexPrep.detailsTitle')}
          </h3>
          <p className="mt-1 text-sm text-faint">{t('flexPrep.detailsHint')}</p>
          <div className="mt-3 grid gap-3">
            <Field label={t('flexPrep.name')} htmlFor="flex-prepare-name">
              <TextInput
                id="flex-prepare-name"
                value={name}
                autoComplete="name"
                onChange={(event) => setName(event.target.value)}
              />
            </Field>
            <Field label={t('flexPrep.email')} htmlFor="flex-prepare-email">
              <TextInput
                id="flex-prepare-email"
                type="email"
                value={email}
                autoComplete="email"
                onChange={(event) => setEmail(event.target.value)}
              />
            </Field>
            <Field label={t('flexPrep.phone')} htmlFor="flex-prepare-phone">
              <TextInput
                id="flex-prepare-phone"
                type="tel"
                value={phone}
                autoComplete="tel"
                onChange={(event) => setPhone(event.target.value)}
              />
            </Field>
          </div>
          <div className="mt-3 flex flex-wrap items-center gap-3">
            <Button size="sm" variant="ghost" onClick={() => void saveDetails()}>
              {t('flexPrep.saveDetails')}
            </Button>
            <span aria-live="polite" className="text-sm text-success">
              {savedDetails ? t('flexPrep.detailsSaved') : ''}
            </span>
          </div>
        </section>

        <section className="mt-5 rounded-lg border border-border p-4" aria-labelledby="flex-prepare-availability">
          <h3 id="flex-prepare-availability" className="text-base font-semibold text-ink">
            {t('flexPrep.availabilityTitle')}
          </h3>
          <p className="mt-1 wrap-anywhere text-base leading-relaxed text-muted">
            {availability || t('flexPrep.availabilityEmpty')}
          </p>
        </section>

        <section className="mt-5 rounded-lg border border-border p-4" aria-labelledby="flex-prepare-message">
          <h3 id="flex-prepare-message" className="text-base font-semibold text-ink">
            {t('flexPrep.messageTitle')}
          </h3>
          <p className="mt-1 text-sm text-faint">{t('flexPrep.messageHint')}</p>
          <label className="mt-3 block" htmlFor="flex-prepare-message-text">
            <span className="sr-only">{t('flexPrep.messageTitle')}</span>
            <textarea
              id="flex-prepare-message-text"
              className="h-56 w-full rounded-md border border-border bg-surface p-3 text-base text-ink outline-none focus:border-accent"
              value={message}
              onChange={(event) => {
                setMessage(event.target.value)
                setDirty(true)
              }}
            />
          </label>
          <div className="mt-2 flex flex-wrap items-center gap-3">
            <Button size="sm" onClick={() => void copyMessage()}>
              {copied ? t('common.copied') : t('common.copy')}
            </Button>
            {dirty && (
              <Button
                size="sm"
                variant="ghost"
                onClick={() => {
                  setMessage(generated)
                  setDirty(false)
                }}
              >
                {t('flexPrep.reset')}
              </Button>
            )}
          </div>
        </section>

        <section className="mt-5 rounded-lg border border-border p-4" aria-labelledby="flex-prepare-card">
          <h3 id="flex-prepare-card" className="text-base font-semibold text-ink">
            {t('flexPrep.cardTitle')}
          </h3>
          <p className="mt-1 text-sm text-faint">{t('flexPrep.cardHint')}</p>
          <div className="mt-3">
            <Button size="sm" variant="ghost" onClick={() => printProfileCard(withContact, de)}>
              {t('flexPrep.cardDownload')}
            </Button>
          </div>
        </section>

        <section className="mt-5 rounded-lg border border-border p-4" aria-labelledby="flex-prepare-route">
          <h3 id="flex-prepare-route" className="text-base font-semibold text-ink">
            {t('flexPrep.routeTitle')}
          </h3>
          <p className="mt-1 wrap-anywhere text-base leading-relaxed text-muted">{t('flexPrep.routeBody')}</p>
          <div className="mt-3">
            <a href={job.url} target="_blank" rel="noreferrer" className="inline-flex">
              <Button variant="accent" size="sm">
                {openEntry ? t('flexible.card.official') : t('flexible.card.apply')}
              </Button>
            </a>
          </div>
          <p className="mt-2 text-sm text-faint">{t('flexPrep.noAutoApply')}</p>
        </section>
      </div>
    </div>
  )
}