/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=worker/wrangler.jsonc --include-runtime=false worker/worker-configuration.d.ts` (hash: 34bc9697a11be60ebff407be69d35907)
interface __BaseEnv_Env {
	ALLOWED_ORIGINS: "https://karpit0499.github.io";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ALLOWED_ORIGINS">> {}
}
