/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=worker/wrangler.jsonc --include-runtime=false worker/worker-configuration.d.ts` (hash: a70d602f4ffa028b0c06539577a068de)
interface __BaseEnv_Env {
	ATS_CACHE: KVNamespace;
	FEEDBACK_DEDUP: KVNamespace;
	FEEDBACK_RATE_LIMITER: RateLimit;
	ALLOWED_ORIGINS: "https://karpit0499.github.io";
	GITHUB_REPO_OWNER: "karpit0499";
	GITHUB_REPO_NAME: "klar";
	TURNSTILE_EXPECTED_HOSTNAMES: "karpit0499.github.io";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ALLOWED_ORIGINS" | "GITHUB_REPO_OWNER" | "GITHUB_REPO_NAME" | "TURNSTILE_EXPECTED_HOSTNAMES">> {}
}
