import type { AtsEntry } from '../registry.de'

/**
 * v2.6.1 expansion: live boards verified 2026-08-11. They are deliberately
 * cache-delivered so a browser never fans out across 100 additional tenants.
 * The evidence-complete audit manifest lives in data/sources/.
 */
export const ATS_CACHE_EXPANSION_DE = [
  {"company":"Capgemini Deutschland","ats":"greenhouse","slug":"capgeminideutschlandgmbh","state":"active","delivery":"worker_cache","verifiedAt":"2026-08-11"},
  {"company":"The Quality Group","ats":"greenhouse","slug":"thequalitygroupgmbh1","state":"active","delivery":"worker_cache","verifiedAt":"2026-08-11"},
  {"company":"Doctolib","ats":"greenhouse","slug":"doctolib","state":"active","delivery":"worker_cache","verifiedAt":"2026-08-11"},
  {"company":"JetBrains","ats":"greenhouse","slug":"jetbrains","state":"active","delivery":"worker_cache","verifiedAt":"2026-08-11"},
  {"company":"Gropyus","ats":"greenhouse","slug":"gropyus","state":"active","delivery":"worker_cache","verifiedAt":"2026-08-11"},
  {"company":"Air Apps","ats":"ashby","slug":"airapps","state":"active","delivery":"worker_cache","verifiedAt":"2026-08-11"},
  {"company":"Almedia","ats":"ashby","slug":"almedia","state":"active","delivery":"worker_cache","verifiedAt":"2026-08-11"},
  {"company":"Veeva Systems","ats":"lever","slug":"veeva","state":"active","delivery":"worker_cache","verifiedAt":"2026-08-11"},
  {"company":"Avelios Medical","ats":"ashby","slug":"avelios-medical","state":"active","delivery":"worker_cache","verifiedAt":"2026-08-11"},
  {"company":"Octopus Energy","ats":"lever","slug":"octoenergy","state":"active","delivery":"worker_cache","verifiedAt":"2026-08-11"},
  {"company":"Fever","ats":"greenhouse","slug":"feverup","state":"active","delivery":"worker_cache","verifiedAt":"2026-08-11"},
  {"company":"Salonkee","ats":"ashby","slug":"salonkee","state":"active","delivery":"worker_cache","verifiedAt":"2026-08-11"},
  {"company":"proALPHA","ats":"greenhouse","slug":"proalphagroup","state":"active","delivery":"worker_cache","verifiedAt":"2026-08-11"},
  {"company":"DEPT","ats":"greenhouse","slug":"dept","state":"active","delivery":"worker_cache","verifiedAt":"2026-08-11"},
  {"company":"Capco","ats":"greenhouse","slug":"capco","state":"active","delivery":"worker_cache","verifiedAt":"2026-08-11"},
  {"company":"Proton","ats":"greenhouse","slug":"proton","state":"active","delivery":"worker_cache","verifiedAt":"2026-08-11"},
  {"company":"AutoScout24","ats":"greenhouse","slug":"autoscout24","state":"active","delivery":"worker_cache","verifiedAt":"2026-08-11"},
  {"company":"Munich Electrification","ats":"ashby","slug":"munich-electrification","state":"active","delivery":"worker_cache","verifiedAt":"2026-08-11"},
  {"company":"n8n","ats":"ashby","slug":"n8n","state":"active","delivery":"worker_cache","verifiedAt":"2026-08-11"},
  {"company":"Qualysoft","ats":"lever","slug":"qualysoft","state":"active","delivery":"worker_cache","verifiedAt":"2026-08-11"},
  {"company":"voize","ats":"ashby","slug":"voize","state":"active","delivery":"worker_cache","verifiedAt":"2026-08-11"},
  {"company":"Avi Medical","ats":"greenhouse","slug":"avimedical","state":"active","delivery":"worker_cache","verifiedAt":"2026-08-11"},
  {"company":"Public Cloud Group","ats":"ashby","slug":"publiccloudgroup","state":"active","delivery":"worker_cache","verifiedAt":"2026-08-11"},
  {"company":"Upvest","ats":"ashby","slug":"upvest","state":"active","delivery":"worker_cache","verifiedAt":"2026-08-11"},
  {"company":"Ebury","ats":"greenhouse","slug":"ebury","state":"active","delivery":"worker_cache","verifiedAt":"2026-08-11"},
  {"company":"Rohlik Group","ats":"ashby","slug":"rohlik","state":"active","delivery":"worker_cache","verifiedAt":"2026-08-11"},
  {"company":"Wellhub","ats":"greenhouse","slug":"gympass","state":"active","delivery":"worker_cache","verifiedAt":"2026-08-11"},
  {"company":"Staffbase","ats":"greenhouse","slug":"staffbase","state":"active","delivery":"worker_cache","verifiedAt":"2026-08-11"},
  {"company":"MOIA","ats":"greenhouse","slug":"moia","state":"active","delivery":"worker_cache","verifiedAt":"2026-08-11"},
  {"company":"smava","ats":"greenhouse","slug":"smavagmbh","state":"active","delivery":"worker_cache","verifiedAt":"2026-08-11"},
  {"company":"RIVR","ats":"lever","slug":"rivr","state":"active","delivery":"worker_cache","verifiedAt":"2026-08-11"},
  {"company":"Sonar","ats":"lever","slug":"sonarsource","state":"active","delivery":"worker_cache","verifiedAt":"2026-08-11"},
  {"company":"Lightspeed Commerce","ats":"ashby","slug":"lightspeedhq","state":"active","delivery":"worker_cache","verifiedAt":"2026-08-11"},
  {"company":"Perk","ats":"ashby","slug":"perk","state":"active","delivery":"worker_cache","verifiedAt":"2026-08-11"},
  {"company":"Sony Music Entertainment","ats":"greenhouse","slug":"sonymusicentertainment","state":"active","delivery":"worker_cache","verifiedAt":"2026-08-11"},
  {"company":"Wemolo","ats":"ashby","slug":"wemolo","state":"active","delivery":"worker_cache","verifiedAt":"2026-08-11"},
  {"company":"Zscaler","ats":"greenhouse","slug":"zscaler","state":"active","delivery":"worker_cache","verifiedAt":"2026-08-11"},
  {"company":"Langdock","ats":"ashby","slug":"langdock","state":"active","delivery":"worker_cache","verifiedAt":"2026-08-11"},
  {"company":"Planet","ats":"greenhouse","slug":"planetlabs","state":"active","delivery":"worker_cache","verifiedAt":"2026-08-11"},
  {"company":"vivenu","ats":"lever","slug":"vivenu","state":"active","delivery":"worker_cache","verifiedAt":"2026-08-11"},
  {"company":"Lemon Markets","ats":"ashby","slug":"lemon-markets","state":"active","delivery":"worker_cache","verifiedAt":"2026-08-11"},
  {"company":"WongDoody","ats":"greenhouse","slug":"wongdoody","state":"active","delivery":"worker_cache","verifiedAt":"2026-08-11"},
  {"company":"Aufinity Group","ats":"ashby","slug":"aufinity-group-gmbh","state":"active","delivery":"worker_cache","verifiedAt":"2026-08-11"},
  {"company":"Awin","ats":"greenhouse","slug":"awin","state":"active","delivery":"worker_cache","verifiedAt":"2026-08-11"},
  {"company":"Galvany","ats":"ashby","slug":"galvany","state":"active","delivery":"worker_cache","verifiedAt":"2026-08-11"},
  {"company":"Satispay","ats":"ashby","slug":"satispay","state":"active","delivery":"worker_cache","verifiedAt":"2026-08-11"},
  {"company":"telli","ats":"ashby","slug":"telli","state":"active","delivery":"worker_cache","verifiedAt":"2026-08-11"},
  {"company":"Yepoda","ats":"ashby","slug":"yepoda","state":"active","delivery":"worker_cache","verifiedAt":"2026-08-11"},
  {"company":"DataGuard","ats":"ashby","slug":"dataguard","state":"active","delivery":"worker_cache","verifiedAt":"2026-08-11"},
  {"company":"GitLab","ats":"greenhouse","slug":"gitlab","state":"active","delivery":"worker_cache","verifiedAt":"2026-08-11"},
  {"company":"Neural Concept","ats":"ashby","slug":"neuralconcept","state":"active","delivery":"worker_cache","verifiedAt":"2026-08-11"},
  {"company":"SoSafe","ats":"ashby","slug":"sosafe","state":"active","delivery":"worker_cache","verifiedAt":"2026-08-11"},
  {"company":"CarOnSale","ats":"greenhouse","slug":"caronsale","state":"active","delivery":"worker_cache","verifiedAt":"2026-08-11"},
  {"company":"Veeam","ats":"greenhouse","slug":"veeamsoftware","state":"active","delivery":"worker_cache","verifiedAt":"2026-08-11"},
  {"company":"Artefact","ats":"greenhouse","slug":"artefact","state":"active","delivery":"worker_cache","verifiedAt":"2026-08-11"},
  {"company":"ClickHouse","ats":"greenhouse","slug":"clickhouse","state":"active","delivery":"worker_cache","verifiedAt":"2026-08-11"},
  {"company":"DKB Code Factory","ats":"greenhouse","slug":"dkbcodefactory","state":"active","delivery":"worker_cache","verifiedAt":"2026-08-11"},
  {"company":"Impossible Cloud","ats":"lever","slug":"impossiblecloud","state":"active","delivery":"worker_cache","verifiedAt":"2026-08-11"},
  {"company":"ZEAL Network","ats":"ashby","slug":"zeal-network","state":"active","delivery":"worker_cache","verifiedAt":"2026-08-11"},
  {"company":"Hawk AI","ats":"ashby","slug":"hawk","state":"active","delivery":"worker_cache","verifiedAt":"2026-08-11"},
  {"company":"Netlight","ats":"lever","slug":"netlight","state":"active","delivery":"worker_cache","verifiedAt":"2026-08-11"},
  {"company":"Apaleo","ats":"greenhouse","slug":"apaleo","state":"active","delivery":"worker_cache","verifiedAt":"2026-08-11"},
  {"company":"FGS Global","ats":"greenhouse","slug":"fgsglobal","state":"active","delivery":"worker_cache","verifiedAt":"2026-08-11"},
  {"company":"KAYAK","ats":"ashby","slug":"kayak","state":"active","delivery":"worker_cache","verifiedAt":"2026-08-11"},
  {"company":"Leapsome","ats":"ashby","slug":"leapsome","state":"active","delivery":"worker_cache","verifiedAt":"2026-08-11"},
  {"company":"Too Good To Go","ats":"greenhouse","slug":"toogoodtogo","state":"active","delivery":"worker_cache","verifiedAt":"2026-08-11"},
  {"company":"Alaika","ats":"greenhouse","slug":"alaika","state":"active","delivery":"worker_cache","verifiedAt":"2026-08-11"},
  {"company":"ElevenLabs","ats":"ashby","slug":"elevenlabs","state":"active","delivery":"worker_cache","verifiedAt":"2026-08-11"},
  {"company":"Eye Security","ats":"ashby","slug":"eye-security","state":"active","delivery":"worker_cache","verifiedAt":"2026-08-11"},
  {"company":"Lucid Motors","ats":"greenhouse","slug":"lucidmotors","state":"active","delivery":"worker_cache","verifiedAt":"2026-08-11"},
  {"company":"Pure Storage","ats":"greenhouse","slug":"purestorage","state":"active","delivery":"worker_cache","verifiedAt":"2026-08-11"},
  {"company":"Soho House","ats":"greenhouse","slug":"sohohouseco","state":"active","delivery":"worker_cache","verifiedAt":"2026-08-11"},
  {"company":"Agicap","ats":"lever","slug":"agicap","state":"active","delivery":"worker_cache","verifiedAt":"2026-08-11"},
  {"company":"Black Forest Labs","ats":"greenhouse","slug":"blackforestlabs","state":"active","delivery":"worker_cache","verifiedAt":"2026-08-11"},
  {"company":"doinstruct","ats":"ashby","slug":"doinstruct","state":"active","delivery":"worker_cache","verifiedAt":"2026-08-11"},
  {"company":"emnify","ats":"greenhouse","slug":"emnify","state":"active","delivery":"worker_cache","verifiedAt":"2026-08-11"},
  {"company":"Via","ats":"greenhouse","slug":"via","state":"active","delivery":"worker_cache","verifiedAt":"2026-08-11"},
  {"company":"Jua","ats":"ashby","slug":"jua","state":"active","delivery":"worker_cache","verifiedAt":"2026-08-11"},
  {"company":"Klim","ats":"ashby","slug":"klim","state":"active","delivery":"worker_cache","verifiedAt":"2026-08-11"},
  {"company":"Melotech","ats":"ashby","slug":"melotech","state":"active","delivery":"worker_cache","verifiedAt":"2026-08-11"},
  {"company":"Mercura","ats":"ashby","slug":"mercura","state":"active","delivery":"worker_cache","verifiedAt":"2026-08-11"},
  {"company":"Mozilla","ats":"greenhouse","slug":"mozilla","state":"active","delivery":"worker_cache","verifiedAt":"2026-08-11"},
  {"company":"Sensmore","ats":"ashby","slug":"sensmore","state":"active","delivery":"worker_cache","verifiedAt":"2026-08-11"},
  {"company":"Tandem Health","ats":"ashby","slug":"tandem-health","state":"active","delivery":"worker_cache","verifiedAt":"2026-08-11"},
  {"company":"Xebia DACH","ats":"greenhouse","slug":"xebiadach","state":"active","delivery":"worker_cache","verifiedAt":"2026-08-11"},
  {"company":"Benchling","ats":"ashby","slug":"benchling","state":"active","delivery":"worker_cache","verifiedAt":"2026-08-11"},
  {"company":"BetterHelp","ats":"greenhouse","slug":"betterhelp","state":"active","delivery":"worker_cache","verifiedAt":"2026-08-11"},
  {"company":"Comstruct","ats":"ashby","slug":"comstruct","state":"active","delivery":"worker_cache","verifiedAt":"2026-08-11"},
  {"company":"Hive","ats":"greenhouse","slug":"hive","state":"active","delivery":"worker_cache","verifiedAt":"2026-08-11"},
  {"company":"Manex","ats":"ashby","slug":"manex","state":"active","delivery":"worker_cache","verifiedAt":"2026-08-11"},
  {"company":"Mapbox","ats":"ashby","slug":"mapbox","state":"active","delivery":"worker_cache","verifiedAt":"2026-08-11"},
  {"company":"OpenAI","ats":"ashby","slug":"openai","state":"active","delivery":"worker_cache","verifiedAt":"2026-08-11"},
  {"company":"PPLwise","ats":"ashby","slug":"pplwise","state":"active","delivery":"worker_cache","verifiedAt":"2026-08-11"},
  {"company":"Praxipal","ats":"ashby","slug":"praxipal","state":"active","delivery":"worker_cache","verifiedAt":"2026-08-11"},
  {"company":"Prior Labs","ats":"ashby","slug":"prior-labs","state":"active","delivery":"worker_cache","verifiedAt":"2026-08-11"},
  {"company":"Trading 212","ats":"ashby","slug":"trading212","state":"active","delivery":"worker_cache","verifiedAt":"2026-08-11"},
  {"company":"Unframe","ats":"greenhouse","slug":"unframe","state":"active","delivery":"worker_cache","verifiedAt":"2026-08-11"},
  {"company":"Valtech","ats":"greenhouse","slug":"valtech","state":"active","delivery":"worker_cache","verifiedAt":"2026-08-11"},
  {"company":"Affinidi","ats":"greenhouse","slug":"affinidi","state":"active","delivery":"worker_cache","verifiedAt":"2026-08-11"},
  {"company":"Carwow","ats":"ashby","slug":"carwow","state":"active","delivery":"worker_cache","verifiedAt":"2026-08-11"},
] satisfies AtsEntry[]
